# Generated by Django 5.0.2 on 2024-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_remove_room_user_room_creator_id_alter_room_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creator_id',
        ),
        migrations.AddField(
            model_name='room',
            name='creator_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
