# Generated by Django 5.0.2 on 2024-04-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat_app', '0004_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creator_name',
        ),
        migrations.AddField(
            model_name='room',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
